#!/bin/bash

#PBS -N OUTPUT
#PBS -l nodes=1:ppn=1
#PBS -l vmem=4gb
#PBS -l walltime=1:00:00
#PBS -M z3403159@student.unsw.edu.au
#PBS -m ae
##PBS -k n
##PBS -t 1-50

cd $PBS_O_WORKDIR
 
module purge
module add mathematica/10.0.1

# - RESP_DIR=`date +'%Y-%m-%d_%H.%M'`
RESP_DIR="$PBS_O_WORKDIR/resp/run_01"

mkdir -p $RESP_DIR
cd $RESP_DIR
xvfb-run --auto-servernum WolframScript -script $PBS_O_WORKDIR/generate.math _J1_ _NSAMPLES_
