#!/bin/bash

#PBS -N OUTPUT
#PBS -l nodes=1:ppn=4
#PBS -l vmem=16gb
#PBS -l walltime=96:00:00
#PBS -M z3403159@student.unsw.edu.au
#PBS -m ae
##PBS -k n
##PBS -t 1-50

cd $PBS_O_WORKDIR
 
module purge
module add mathematica/10.0.1

# - RESP_DIR=`date +'%Y-%m-%d_%H.%M'`
RESP_DIR="$PBS_O_WORKDIR/resp/run_09"

mkdir -p $RESP_DIR
cd $RESP_DIR
WolframScript -script $PBS_O_WORKDIR/generate-data-beta.m 'DaubechiesWavelet[4]' '-2' '5'
